CREATE PROC FI_SP_ConsBeneficiario
	@ID BIGINT
AS
BEGIN
	IF(ISNULL(@ID,0) = 0)
		SELECT ID, NOME, IDCLIENTE, CPF FROM BENEFICIARIOS WITH(NOLOCK)
	ELSE
		SELECT ID, NOME, IDCLIENTE, CPF FROM BENEFICIARIOS WITH(NOLOCK) WHERE ID = @ID
END