CREATE PROC FI_SP_PesqBeneficiario
	@ID BIGINT
AS
BEGIN
	IF(ISNULL(@ID,0) = 0)
		SELECT ID, NOME, IDCLIENTE, CPF FROM BENEFICIARIOS WITH(NOLOCK)
	ELSE
		SELECT ID, NOME, IDCLIENTE, CPF FROM BENEFICIARIOS WITH(NOLOCK) WHERE IDCLIENTE = @ID
END